Algoritmo "semnome"


Var

   a, b, c, maior : real

Inicio

   escreval("Digite as três distâncias: ")
   leia(a, b, c)
   
     se (a > b) e (a > c) entao
      maior <- a
      senao
       se b > C entao
       maior <- b
       senao
        se c > b entao
        maior <- c
        fimse
       fimse
     fimse
     
     escreval("Maior distância: ", maior)




Fimalgoritmo